# ---
# - name: Install Jenkins in target nodes
#   hosts: all
#   become: true
#   tasks:
#     - name: Wait for APT lock to be released
#       wait_for:
#         path: /var/lib/dpkg/lock-frontend
#         state: absent
#         timeout: 500

#     - name: Update APT cache
#       apt:
#         update_cache: yes
#       # register: apt_update_result
#       # retries: 10  # Increased retries
#       # delay: 20    # Increased delay to 20 seconds
#       # until: apt_update_result is succeeded

#     - name: Install OpenJDK
#       apt:
#         name: openjdk-11-jre
#         state: present
#       # register: openjdk_install_result
#       # retries: 10
#       # delay: 20
#       # until: openjdk_install_result is succeeded

#     - name: Install Maven
#       apt:
#         name: maven
#         state: present
#       # register: maven_install_result
#       # retries: 10
#       # delay: 20
#       # until: maven_install_result is succeeded

#     - name: Install Ansible
#       apt:
#         name: ansible
#         state: present
#       # register: ansible_install_result
#       # retries: 10
#       # delay: 20
#       # until: ansible_install_result is succeeded

#     - name: Install MySQL
#       apt:
#         name: mysql-server
#         state: present
#       # register: mysql_install_result
#       # retries: 10
#       # delay: 20
#       # until: mysql_install_result is succeeded


---
- name: Install Jenkins in target nodes
  hosts: all
  become: true
  tasks:

    - name: Check if APT is locked
      shell: |
        if [ -e /var/lib/dpkg/lock-frontend ]; then
          echo "locked"
        else
          echo "not_locked"
        fi
      register: apt_lock_status
      changed_when: false

    - name: Kill existing APT processes if locked
      shell: |
        if [ "{{ apt_lock_status.stdout }}" == "locked" ]; then
          for pid in $(pgrep -f 'apt'); do
            echo "Killing process $pid"
            kill -9 $pid
          done
        fi
      become: true
      changed_when: false
      retries: 3
      delay: 10


    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jre
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present




