---
- name: Install Jenkins and dependencies on target nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure APT lock is handled gracefully
      ansible.builtin.shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
          echo "Waiting for APT lock...";
          sleep 10;
        done
      become: true
      retries: 5
      delay: 10
      until: "'/var/lib/dpkg/lock' not in ansible_facts.packages"

    - name: Update APT cache
      apt:
        update_cache: yes
      register: apt_update_result
      retries: 5
      delay: 10
      until: apt_update_result is succeeded

    - name: Install OpenJDK, Maven, Ansible, and MySQL
      apt:
        name:
          - openjdk-11-jre
          - maven
          - ansible
          - mysql-server
        state: present
        force: yes
        dpkg_options:
          - "force-confold"
      register: install_packages_result
      retries: 5
      delay: 10
      until: install_packages_result is succeeded

    - name: Clean up APT lock management script
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/99disable-lock
        state: absent
      become: true
