---
- name: Perform Various System Operations
  hosts: all
  become: true
  tasks:

    # File Operations
    - name: Copy configuration file
      ansible.builtin.copy:
        src: /path/to/local/config.conf
        dest: /etc/myapp/config.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create a directory
      ansible.builtin.file:
        path: /var/myapp
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Set file permissions
      ansible.builtin.file:
        path: /etc/myapp/config.conf
        mode: '0644'

    # User and Group Management
    - name: Create a new user
      ansible.builtin.user:
        name: newuser
        state: present
        shell: /bin/bash

    - name: Add user to a group
      ansible.builtin.user:
        name: newuser
        groups: sudo
        append: yes

    - name: Remove a user
      ansible.builtin.user:
        name: olduser
        state: absent

    # Configuration Management
    - name: Deploy application configuration
      ansible.builtin.template:
        src: /path/to/templates/app.conf.j2
        dest: /etc/myapp/app.conf
        owner: root
        group: root
        mode: '0644'

    # System Monitoring and Reporting
    - name: Gather system facts
      ansible.builtin.setup:

    - name: Report disk usage
      ansible.builtin.shell: df -h
      register: disk_usage

    - name: Display disk usage
      ansible.builtin.debug:
        msg: "{{ disk_usage.stdout }}"

    # Networking (Optional, if needed)
    - name: Configure network interface
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        line: 'iface eth0 inet static'
        create: yes

    - name: Ensure firewall is configured
      ansible.builtin.ufw:
        rule: allow
        name: 'Open port 80'
        port: 80
        state: enabled
