---
- name: Install Jenkins in target nodes
  hosts: all
  become: true
  tasks:
    # - name: Wait for APT lock to be released
    #   wait_for:
    #     path: /var/lib/dpkg/lock
    #     state: absent
    #     timeout: 600  # Increased timeout to 10 minutes

    - name: Update APT cache
      apt:
        update_cache: yes
      retries: 10  # Increased retries
      delay: 20    # Increased delay to 20 seconds
      until: result is succeeded

    - name: Update nodes
      apt:
        update_cache: yes
      retries: 10
      delay: 20
      until: result is succeeded

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jre
        state: present
      retries: 10
      delay: 20
      until: result is succeeded

    - name: Install Maven
      apt:
        name: maven
        state: present
      retries: 10
      delay: 20
      until: result is succeeded

    - name: Install Ansible
      apt:
        name: ansible
        state: present
      retries: 10
      delay: 20
      until: result is succeeded

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      retries: 10
      delay: 20
      until: result is succeeded
