---
- name: Install Jenkins and dependencies on target nodes
  hosts: all
  become: true
  tasks:
    - name: Temporarily disable APT lock
      ansible.builtin.command: |
        echo 'APT::Acquire::Retries "0";' > /etc/apt/apt.conf.d/99disable-lock
      become: true

    - name: Update APT cache
      apt:
        update_cache: yes
      retries: 5
      delay: 5
      until: apt_cache_result is succeeded
      register: apt_cache_result

    - name: Install OpenJDK, Maven, Ansible, and MySQL
      ansible.builtin.command: |
        DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --force-conflicts openjdk-11-jre maven ansible mysql-server
      become: true
      register: install_packages_result
      retries: 5
      delay: 5
      until: install_packages_result is succeeded

    - name: Re-enable APT lock
      ansible.builtin.command: rm -f /etc/apt/apt.conf.d/99disable-lock
      become: true
