---
- name: Remove Jenkins-related packages from target nodes
  hosts: all
  become: true
  tasks:
    - name: Remove OpenJDK
      apt:
        name: openjdk-11-jre
        state: absent
      register: openjdk_remove_result
      retries: 10
      delay: 20
      until: openjdk_remove_result is succeeded

    - name: Remove Maven
      apt:
        name: maven
        state: absent
      register: maven_remove_result
      retries: 10
      delay: 20
      until: maven_remove_result is succeeded

    - name: Remove Ansible
      apt:
        name: ansible
        state: absent
      register: ansible_remove_result
      retries: 10
      delay: 20
      until: ansible_remove_result is succeeded

    - name: Remove MySQL
      apt:
        name: mysql-server
        state: absent
      register: mysql_remove_result
      retries: 10
      delay: 20
      until: mysql_remove_result is succeeded
