---
- name: Install jenkins in target nodes
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install curl, openjdk
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
          - curl
          - openjdk-17-jre

    - name: Update nodes
      become: true
      apt:
        update_cache: yes

    - name: Install docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Install openjdk
      become: true
      apt:
        name: openjdk-11-jre
        state: present

    - name: Install maven
      apt:
        name: maven
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: install mysql
      become: true
      apt:
        name: mysql-server
        state: present
